version: "3.9"

#  Const Values
# --------------------------------------------------
x-const:
  hostname:
    bastion: &HOSTNAME_BASTION
      "bastion"
    target: &HOSTNAME_TARGET
      "target"

#  Services
# --------------------------------------------------
services:
  bastion:
    build:
      args:
        GID: 1000
        UID: 1000
        HOSTNAME: *HOSTNAME_BASTION
      dockerfile: docker/host.Dockerfile
    container_name: *HOSTNAME_BASTION
    hostname: *HOSTNAME_BASTION
    image: fpc-bastion
    networks:
      - internal
    ports:
      - '22222:22'
    stdin_open: true
    tty: true
  target:
    build:
      args:
        GID: 1000
        UID: 1000
        HOSTNAME: *HOSTNAME_TARGET
      dockerfile: docker/host.Dockerfile
    container_name: *HOSTNAME_TARGET
    hostname: *HOSTNAME_TARGET
    image: fpc-target
    networks:
      - internal
    ports:
      - '22223:22'
    stdin_open: true
    tty: true

#  Networks
# --------------------------------------------------
networks:
  internal:
    name: internal
